//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsWebsite.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIVIET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAIVIET()
        {
            this.BINHCHON = new HashSet<BINHCHON>();
            this.BINHLUAN = new HashSet<BINHLUAN>();
            this.DANHGIA = new HashSet<DANHGIA>();
        }
    
        public int ID_BAIVIET { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> ID_THELOAI { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public Nullable<int> TACGIA_ID { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHCHON> BINHCHON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUAN> BINHLUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIA { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
