//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsWebsite.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TinTucDBEntities : DbContext
    {
        public TinTucDBEntities()
            : base("name=TinTucDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAIVIET> BAIVIET { get; set; }
        public virtual DbSet<BINHCHON> BINHCHON { get; set; }
        public virtual DbSet<BINHLUAN> BINHLUAN { get; set; }
        public virtual DbSet<DANHGIA> DANHGIA { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<THELOAI> THELOAI { get; set; }
    }
}
